### ISSUE TITLE
Assalamualaikum, punten mas. Perihal password project apakah bisa di share? kebetulan mau ngecheck apknya siapatau bisa dijadikan referensi

### ISSUE THREAD

**Issue by fadilaa** [andrebhas/sitasor#3]
Assalamualaikum mas, saya ijin bertanya. Apakah untuk project ini, passwordnya bisa dibagikan? saya kebetulan lagi mencari referensi untuk project tugas akhir yang memiliki konsep hampir sama dengan project masnya namun dengan kasus yang berbeda. Akan sangat baik apabila dari referensi ini bisa memberikan beberapa gambaran yang bisa saya kerjakan di project saya. Terimakasih sebelumnya mas. Wassalamualaikum.

**Comment by andrebhas** [comment]
Walaikumsalam.
Project ini sudah tidak di maintenance lagi, beberapa backup db dan sourcenya sudah hilang di laptop lama.
Kalau butuh project seperti ini saya bisa buatkan ulang untuk mbak @fadilaa , silanhkan hubungi saya melalui eMail / WA

**Comment by fadilaa** [comment]
Perihal nomer WA mas andre bisa di share?

**Comment by andrebhas** [comment]
089612817010
